UPDATE profiles SET full_name='박순병', role='owner', department='김포공장공정팀', phone='010-2598-0241', contact_email='soonbyoung.park@tongyanginc.co.kr', is_active=true WHERE employee_id='101690';
UPDATE profiles SET full_name='이겨울산', role='owner', department='안양공장공정팀', phone='010-9462-4793', contact_email='geouulsan.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101691';
UPDATE profiles SET full_name='이용진', role='owner', department='김포공장공정팀', phone='010-9986-3956', contact_email='leeyj@tongyanginc.co.kr', is_active=true WHERE employee_id='101692';
UPDATE profiles SET full_name='윤병석', role='owner', department='김포공장', phone='010-9977-4674', contact_email='ybs@tongyanginc.co.kr', is_active=true WHERE employee_id='101693';
UPDATE profiles SET full_name='이춘원', role='owner', department='보령발전본부 저탄장 옥내화사업 토목공사', phone='010-4156-7629', contact_email='chlee@tongyanginc.co.kr', is_active=true WHERE employee_id='101699';
UPDATE profiles SET full_name='이정명', role='owner', department='정관공장품질관리실', phone='010-4105-0060', contact_email='ljm3676@tongyanginc.co.kr', is_active=true WHERE employee_id='101700';
UPDATE profiles SET full_name='한승엽', role='owner', department='아산공장품질관리실', phone='010-7637-1080', contact_email='gkstmdduq11@tongyanginc.co.kr', is_active=true WHERE employee_id='101702';
UPDATE profiles SET full_name='김주현', role='owner', department='서부산공장영업팀', phone='010-4465-4835', contact_email='juhyun.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101703';
UPDATE profiles SET full_name='권황덕', role='owner', department='양산공장영업팀', phone='010-2340-9107', contact_email='kwd3001@tongyanginc.co.kr', is_active=true WHERE employee_id='101704';
UPDATE profiles SET full_name='최지성', role='owner', department='정관공장영업팀', phone='010-2955-3918', contact_email='jisung@tongyanginc.co.kr', is_active=true WHERE employee_id='101705';
UPDATE profiles SET full_name='배호열', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-4513-2448', contact_email='bhy@tongyanginc.co.kr', is_active=true WHERE employee_id='101707';
UPDATE profiles SET full_name='신의진', role='owner', department='인천공장영업팀', phone='010-7926-1000', contact_email='beearlybird@tongyanginc.co.kr', is_active=true WHERE employee_id='101709';
UPDATE profiles SET full_name='이태호', role='owner', department='건자재유통사업팀(구매영업1Part)', phone='010-6880-8870', contact_email='thlee@tongyanginc.co.kr', is_active=true WHERE employee_id='101712';
UPDATE profiles SET full_name='이성운', role='owner', department='가마지천 수해상습지 개선공사', phone='010-8877-0782', contact_email='lsu@tongyanginc.co.kr', is_active=true WHERE employee_id='101721';
UPDATE profiles SET full_name='구동원', role='owner', department='인사팀', phone='010-9192-9265', contact_email='dwkoo@tongyanginc.co.kr', is_active=true WHERE employee_id='101723';
UPDATE profiles SET full_name='김민수', role='owner', department='P.I TFT', phone='010-3585-0212', contact_email='kms@tongyanginc.co.kr', is_active=true WHERE employee_id='101724';
UPDATE profiles SET full_name='백창현', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-3438-6265', contact_email='bch@tongyanginc.co.kr', is_active=true WHERE employee_id='101725';
UPDATE profiles SET full_name='이현아', role='owner', department='인사팀', phone='010-7427-0209', contact_email='hello@tongyanginc.co.kr', is_active=true WHERE employee_id='101727';
UPDATE profiles SET full_name='박명찬', role='owner', department='총무팀(지원파트)', phone='010-9321-0417', contact_email='mcpark@tongyanginc.co.kr', is_active=true WHERE employee_id='101728';
UPDATE profiles SET full_name='고유건', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-4222-8845', contact_email='kyg@tongyanginc.co.kr', is_active=true WHERE employee_id='101729';
UPDATE profiles SET full_name='정연우', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-5678-1819', contact_email='jyw@tongyanginc.co.kr', is_active=true WHERE employee_id='101736';
UPDATE profiles SET full_name='이제원', role='owner', department='골재사업소부산크라샤공정팀', phone='010-3165-2409', contact_email='jeawon.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101737';
UPDATE profiles SET full_name='김정현', role='owner', department='대구공장공정팀', phone='010-4140-2057', contact_email='jhk@tongyanginc.co.kr', is_active=true WHERE employee_id='101738';
UPDATE profiles SET full_name='박상협', role='owner', department='보령발전본부 저탄장 옥내화사업 토목공사', phone='010-4737-3844', contact_email='psh@tongyanginc.co.kr', is_active=true WHERE employee_id='101739';
UPDATE profiles SET full_name='윤유희', role='owner', department='보령발전본부 저탄장 옥내화사업 토목공사', phone='010-8734-6264', contact_email='yyh@tongyanginc.co.kr', is_active=true WHERE employee_id='101740';
UPDATE profiles SET full_name='장원종', role='owner', department='인천공장품질관리실', phone='010-4442-3489', contact_email='jwj22@tongyanginc.co.kr', is_active=true WHERE employee_id='101743';
UPDATE profiles SET full_name='유건우', role='owner', department='골재사업소부산크라샤공정팀', phone='010-4072-8854', contact_email='ygw1213@tongyanginc.co.kr', is_active=true WHERE employee_id='101744';
UPDATE profiles SET full_name='전지훈', role='owner', department='정관공장영업팀', phone='010-7999-8562', contact_email='jihun@tongyanginc.co.kr', is_active=true WHERE employee_id='101745';
UPDATE profiles SET full_name='최필식', role='owner', department='인천공장품질관리실', phone='010-3745-8973', contact_email='cps@tongyanginc.co.kr', is_active=true WHERE employee_id='101749';
UPDATE profiles SET full_name='임채연', role='owner', department='건자재유통사업팀', phone='010-7574-3643', contact_email='lcy@tongyanginc.co.kr', is_active=true WHERE employee_id='101752';
UPDATE profiles SET full_name='황수민', role='owner', department='인천공장영업팀', phone='010-2880-1955', contact_email='sumin92@tongyanginc.co.kr', is_active=true WHERE employee_id='101764';
UPDATE profiles SET full_name='김숙경', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-3566-7556', contact_email='ksk@tongyanginc.co.kr', is_active=true WHERE employee_id='101773';
UPDATE profiles SET full_name='임철진', role='owner', department='서부산공장공정팀', phone='010-7566-0583', contact_email='cjlim1357@tongyanginc.co.kr', is_active=true WHERE employee_id='101779';
UPDATE profiles SET full_name='서정훈', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-8778-4645', contact_email='jhs@tongyanginc.co.kr', is_active=true WHERE employee_id='101780';
UPDATE profiles SET full_name='정상일', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-4319-5863', contact_email='sij@tongyanginc.co.kr', is_active=true WHERE employee_id='101781';
UPDATE profiles SET full_name='오충환', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-7308-8569', contact_email='och@tongyanginc.co.kr', is_active=true WHERE employee_id='101784';
UPDATE profiles SET full_name='남경주', role='owner', department='부산공장영업팀', phone='010-8489-0553', contact_email='kjnam@tongyanginc.co.kr', is_active=true WHERE employee_id='101792';
UPDATE profiles SET full_name='공상훈', role='owner', department='법무팀', phone='010-8602-5414', contact_email='rhdtkdgns114@tongyanginc.co.kr', is_active=true WHERE employee_id='101795';
UPDATE profiles SET full_name='이동호', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-2214-9474', contact_email='ldh@tongyanginc.co.kr', is_active=true WHERE employee_id='101802';
UPDATE profiles SET full_name='신정호', role='owner', department='국회대로 지하차도 및 상부공원화(2단계)건설공사 1공구', phone='010-8903-3923', contact_email='sjh@tongyanginc.co.kr', is_active=true WHERE employee_id='101806';
UPDATE profiles SET full_name='안현진', role='owner', department='김포공장영업팀', phone='010-9911-9140', contact_email='hyunjin@tongyanginc.co.kr', is_active=true WHERE employee_id='101807';
UPDATE profiles SET full_name='김경대', role='owner', department='골재사업소부산크라샤공정팀', phone='010-6660-9315', contact_email='kkd@tongyanginc.co.kr', is_active=true WHERE employee_id='101810';
UPDATE profiles SET full_name='신성식', role='owner', department='창원공장영업팀', phone='010-9312-9947', contact_email='seongsik17@tongyanginc.co.kr', is_active=true WHERE employee_id='101811';
UPDATE profiles SET full_name='신상호', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-2213-1347', contact_email='ssh@tongyanginc.co.kr', is_active=true WHERE employee_id='101812';
UPDATE profiles SET full_name='문종호', role='owner', department='안양공장품질관리실', phone='010-7272-3848', contact_email='dlack123@tongyanginc.co.kr', is_active=true WHERE employee_id='101815';
UPDATE profiles SET full_name='김태호', role='owner', department='아산공장공정팀', phone='010-7661-4419', contact_email='kimtaeho@tongyanginc.co.kr', is_active=true WHERE employee_id='101820';
UPDATE profiles SET full_name='황지환', role='owner', department='김해공장관리팀', phone='010-2514-9658', contact_email='hjh9658@tongyanginc.co.kr', is_active=true WHERE employee_id='101829';
UPDATE profiles SET full_name='이종태', role='owner', department='회전기사업/VPC(설계Part)', phone='010-4912-0150', contact_email='ljt@tongyanginc.co.kr', is_active=true WHERE employee_id='101835';
UPDATE profiles SET full_name='김민석', role='owner', department='제주공장영업팀', phone='010-3920-9502', contact_email='minsuk201@tongyanginc.co.kr', is_active=true WHERE employee_id='101837';
UPDATE profiles SET full_name='박한진', role='owner', department='내부회계팀', phone='010-4529-5437', contact_email='phjin@tongyanginc.co.kr', is_active=true WHERE employee_id='101842';
