UPDATE profiles SET full_name='정진학', role='owner', department='그룹커뮤니케이션실', phone='010-3730-6812', contact_email='hoam1@tongyanginc.co.kr', is_active=true WHERE employee_id='100001';
UPDATE profiles SET full_name='배현석', role='owner', department='레미콘사업본부', phone='010-4204-6397', contact_email='hyunseok.bae@tongyanginc.co.kr', is_active=true WHERE employee_id='100013';
UPDATE profiles SET full_name='김종택', role='owner', department='건설부문', phone='010-3242-6842', contact_email='jongtaek.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='100023';
UPDATE profiles SET full_name='황병욱', role='owner', department='회전기사업본부', phone='010-3735-1059', contact_email='bwhwang@tongyanginc.co.kr', is_active=true WHERE employee_id='100033';
UPDATE profiles SET full_name='권오정', role='owner', department='개발금융전략담당', phone='010-6242-4387', contact_email='ojkweon@tongyanginc.co.kr', is_active=true WHERE employee_id='100035';
UPDATE profiles SET full_name='박주형', role='owner', department='대표이사', phone='010-9226-3032', contact_email='j.park@tongyanginc.co.kr', is_active=true WHERE employee_id='100036';
UPDATE profiles SET full_name='정원영', role='owner', department='리스크관리담당', phone='010-2311-9675', contact_email='jwy810@eugenes.co.kr', is_active=true WHERE employee_id='100039';
UPDATE profiles SET full_name='고현구', role='controller', department='사업관리팀', phone='010-4395-5395', contact_email='hgkoh@tongyanginc.co.kr', is_active=true WHERE employee_id='101002';
UPDATE profiles SET full_name='권오복', role='controller', department='광양 바이오매스 EPC 건설공사', phone='010-2776-3486', contact_email='kob1216@tongyanginc.co.kr', is_active=true WHERE employee_id='101003';
UPDATE profiles SET full_name='김두식', role='controller', department='회전기영업팀(영업1Part)', phone='010-3567-2253', contact_email='dskim@tongyanginc.co.kr', is_active=true WHERE employee_id='101005';
UPDATE profiles SET full_name='김병찬', role='owner', department='연구개발팀', phone='010-3001-7121', contact_email='bckim@tongyanginc.co.kr', is_active=true WHERE employee_id='101006';
UPDATE profiles SET full_name='김순배', role='owner', department='보령발전본부 저탄장 옥내화사업 토목공사', phone='010-6326-4010', contact_email='sunbea.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101008';
UPDATE profiles SET full_name='김영주', role='owner', department='예산공장', phone='010-8607-5275', contact_email='zeroland@tongyanginc.co.kr', is_active=true WHERE employee_id='101009';
UPDATE profiles SET full_name='김우경', role='owner', department='해외(북경 순동레미콘)', phone='010-3811-9299', contact_email='wookyung.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101010';
UPDATE profiles SET full_name='김학현', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-8806-3377', contact_email='khh@tongyanginc.co.kr', is_active=true WHERE employee_id='101013';
UPDATE profiles SET full_name='문성철', role='owner', department='회전기영업팀(영업1Part)', phone='010-6553-0707', contact_email='scmoon@tongyanginc.co.kr', is_active=true WHERE employee_id='101015';
UPDATE profiles SET full_name='배치중', role='controller', department='채권관리팀', phone='010-4589-4631', contact_email='chijoong.bae@tongyanginc.co.kr', is_active=true WHERE employee_id='101020';
UPDATE profiles SET full_name='손근호', role='owner', department='골재사업소', phone='010-3594-2298', contact_email='keunho.son@tongyanginc.co.kr', is_active=true WHERE employee_id='101021';
UPDATE profiles SET full_name='송기형', role='owner', department='회전기사업/VPC(설계Part)', phone='010-8588-5987', contact_email='kihyung.song@tongyanginc.co.kr', is_active=true WHERE employee_id='101022';
UPDATE profiles SET full_name='송성원', role='owner', department='수주영업팀', phone='010-3476-6073', contact_email='sungwon.song@tongyanginc.co.kr', is_active=true WHERE employee_id='101023';
UPDATE profiles SET full_name='안준수', role='controller', department='인사팀', phone='010-2294-9760', contact_email='safetyjs@tongyanginc.co.kr', is_active=true WHERE employee_id='101024';
UPDATE profiles SET full_name='유용민', role='controller', department='보령발전본부 저탄장 옥내화사업 토목공사', phone='010-2753-8821', contact_email='yongmin.ryu@tongyanginc.co.kr', is_active=true WHERE employee_id='101029';
UPDATE profiles SET full_name='이종면', role='controller', department='공사관리팀', phone='010-2758-4087', contact_email='jongmyun.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101033';
UPDATE profiles SET full_name='정운영', role='controller', department='울산공장품질관리실', phone='010-2498-2927', contact_email='woonyoung.jeong@tongyanginc.co.kr', is_active=true WHERE employee_id='101035';
UPDATE profiles SET full_name='조민석', role='owner', department='회전기영업팀(영업1Part)', phone='010-8812-7558', contact_email='minseok.cho@tongyanginc.co.kr', is_active=true WHERE employee_id='101038';
UPDATE profiles SET full_name='최재권', role='controller', department='부산공장품질관리실', phone='010-2413-8305', contact_email='jaekwon.choi@tongyanginc.co.kr', is_active=true WHERE employee_id='101042';
UPDATE profiles SET full_name='한두인', role='owner', department='회전기영업팀(영업1Part)', phone='010-4913-9637', contact_email='dooin.han@tongyanginc.co.kr', is_active=true WHERE employee_id='101043';
UPDATE profiles SET full_name='한현철', role='owner', department='회전기영업팀(영업1Part)', phone='010-7744-2946', contact_email='hyunchuel.han@tongyanginc.co.kr', is_active=true WHERE employee_id='101044';
UPDATE profiles SET full_name='황부익', role='controller', department='전략기획팀', phone='010-3686-3973', contact_email='booik.hwang@tongyanginc.co.kr', is_active=true WHERE employee_id='101045';
UPDATE profiles SET full_name='강낙현', role='owner', department='인천공장영업팀', phone='010-5424-7321', contact_email='nakhyeon.kang@tongyanginc.co.kr', is_active=true WHERE employee_id='101046';
UPDATE profiles SET full_name='고연종', role='owner', department='안양공장품질관리실', phone='010-3292-1385', contact_email='yunjong.goh@tongyanginc.co.kr', is_active=true WHERE employee_id='101049';
UPDATE profiles SET full_name='고종범', role='owner', department='아산공장품질관리실', phone='010-3004-4156', contact_email='jongbum.goh@tongyanginc.co.kr', is_active=true WHERE employee_id='101050';
UPDATE profiles SET full_name='김동신', role='owner', department='회계팀', phone='010-3204-8106', contact_email='dongshin.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101053';
UPDATE profiles SET full_name='김만우', role='owner', department='예산공장(생산관리Part)', phone='010-5434-7194', contact_email='manwoo.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101054';
UPDATE profiles SET full_name='김산해', role='owner', department='김해공장영업팀', phone='010-3682-5936', contact_email='hae.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101055';
UPDATE profiles SET full_name='김상률', role='controller', department='대구공장품질관리실', phone='010-3507-5682', contact_email='sangryul.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101056';
UPDATE profiles SET full_name='김영철', role='owner', department='기술관리팀', phone='010-7582-8813', contact_email='youngcheol.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101058';
UPDATE profiles SET full_name='김윤관', role='owner', department='회전기사업/VPC', phone='010-5299-3981', contact_email='yunkwan.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101059';
UPDATE profiles SET full_name='김의돈', role='owner', department='영남권 통합영업담당', phone='010-9301-8279', contact_email='euidon.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101060';
UPDATE profiles SET full_name='김종필', role='controller', department='제주공장품질관리실', phone='010-4207-5370', contact_email='jongpil.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101061';
UPDATE profiles SET full_name='김종학', role='owner', department='전주공장영업팀', phone='010-4010-0052', contact_email='jonghak.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101062';
UPDATE profiles SET full_name='김준', role='owner', department='사업관리팀', phone='010-3858-0779', contact_email='joon.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101063';
UPDATE profiles SET full_name='김준오', role='owner', department='광양 바이오매스 EPC 건설공사', phone='010-2747-6802', contact_email='junoh.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101064';
UPDATE profiles SET full_name='김진희', role='controller', department='김해공장품질관리실', phone='010-4589-6829', contact_email='jinhee4.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101065';
UPDATE profiles SET full_name='김한성', role='owner', department='회전기영업팀(영업1Part)', phone='010-5619-3849', contact_email='khansung@tongyanginc.co.kr', is_active=true WHERE employee_id='101066';
UPDATE profiles SET full_name='김형욱', role='owner', department='전략기획팀', phone='010-7134-7422', contact_email='hwkim@tongyanginc.co.kr', is_active=true WHERE employee_id='101067';
UPDATE profiles SET full_name='나일균', role='owner', department='광양 바이오매스 EPC 건설공사', phone='010-4780-2649', contact_email='ikna@tongyanginc.co.kr', is_active=true WHERE employee_id='101069';
UPDATE profiles SET full_name='모종관', role='controller', department='군산공장품질관리실', phone='010-5265-8567', contact_email='jonggwan.mo@tongyanginc.co.kr', is_active=true WHERE employee_id='101070';
UPDATE profiles SET full_name='문종녕', role='controller', department='회전기사업/VPC', phone='010-6373-3368', contact_email='jongnyung.moon@tongyanginc.co.kr', is_active=true WHERE employee_id='101072';
UPDATE profiles SET full_name='문황모', role='owner', department='회전기영업팀(영업2Part)', phone='010-8627-1337', contact_email='hwangmo.moon@tongyanginc.co.kr', is_active=true WHERE employee_id='101073';
