UPDATE profiles SET full_name='김형욱', role='owner', department='전략기획팀', phone='010-8542-0406', contact_email='hyungwook2.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101140';
UPDATE profiles SET full_name='김휘종', role='controller', department='예산공장(생산관리Part)', phone='010-7512-1291', contact_email='huijong.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101141';
UPDATE profiles SET full_name='나형동', role='owner', department='인사팀', phone='010-6226-5234', contact_email='nhd@tongyanginc.co.kr', is_active=true WHERE employee_id='101142';
UPDATE profiles SET full_name='노형철', role='owner', department='회전기영업팀(영업1Part)', phone='010-4176-2293', contact_email='hcroh@tongyanginc.co.kr', is_active=true WHERE employee_id='101143';
UPDATE profiles SET full_name='박광원', role='owner', department='보령발전본부 저탄장 옥내화사업 토목공사', phone='010-5026-0105', contact_email='kwpark@tongyanginc.co.kr', is_active=true WHERE employee_id='101144';
UPDATE profiles SET full_name='박준수', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-2313-4296', contact_email='junsu1.park@tongyanginc.co.kr', is_active=true WHERE employee_id='101146';
UPDATE profiles SET full_name='방진욱', role='owner', department='연구개발팀', phone='010-9445-1812', contact_email='jinwook.bang@tongyanginc.co.kr', is_active=true WHERE employee_id='101148';
UPDATE profiles SET full_name='배정한', role='owner', department='서부산공장관리팀', phone='010-9855-2470', contact_email='jeonghan.bae@tongyanginc.co.kr', is_active=true WHERE employee_id='101149';
UPDATE profiles SET full_name='서동현', role='owner', department='회계팀', phone='010-8293-5855', contact_email='donghyun2.seo@tongyanginc.co.kr', is_active=true WHERE employee_id='101151';
UPDATE profiles SET full_name='신응식', role='owner', department='예산공장(생산관리Part)', phone='010-3401-5710', contact_email='eungsik.shin@tongyanginc.co.kr', is_active=true WHERE employee_id='101152';
UPDATE profiles SET full_name='안재욱', role='owner', department='파주공장품질관리실', phone='010-3287-3297', contact_email='jaewook.ahn@tongyanginc.co.kr', is_active=true WHERE employee_id='101153';
UPDATE profiles SET full_name='안홍준', role='owner', department='공사관리팀', phone='010-7130-3154', contact_email='hongjoon.ahn@tongyanginc.co.kr', is_active=true WHERE employee_id='101154';
UPDATE profiles SET full_name='양성호', role='owner', department='서부산공장영업팀', phone='010-3524-7355', contact_email='sungho.yang@tongyanginc.co.kr', is_active=true WHERE employee_id='101155';
UPDATE profiles SET full_name='양태진', role='owner', department='전주공장품질관리실', phone='010-2881-2123', contact_email='taejin.yang@tongyanginc.co.kr', is_active=true WHERE employee_id='101156';
UPDATE profiles SET full_name='여환열', role='owner', department='사업운영팀', phone='010-3688-7549', contact_email='hwanyol.yeo@tongyanginc.co.kr', is_active=true WHERE employee_id='101157';
UPDATE profiles SET full_name='오영유', role='owner', department='파주공장영업팀', phone='010-8626-3154', contact_email='youngyu.oh@tongyanginc.co.kr', is_active=true WHERE employee_id='101159';
UPDATE profiles SET full_name='위성화', role='owner', department='채권관리팀', phone='010-9836-9600', contact_email='seonghwa.wi@tongyanginc.co.kr', is_active=true WHERE employee_id='101160';
UPDATE profiles SET full_name='유병욱', role='owner', department='창원공장영업팀', phone='010-5593-7809', contact_email='byungwook.yoo@tongyanginc.co.kr', is_active=true WHERE employee_id='101161';
UPDATE profiles SET full_name='윤태식', role='owner', department='안양공장영업팀', phone='010-3514-1428', contact_email='taesig.yoon@tongyanginc.co.kr', is_active=true WHERE employee_id='101163';
UPDATE profiles SET full_name='이병렬', role='owner', department='서부산공장품질관리실', phone='010-8947-0479', contact_email='byeongryul.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101165';
UPDATE profiles SET full_name='이성일', role='owner', department='공사관리팀', phone='010-8613-7441', contact_email='sungil.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101166';
UPDATE profiles SET full_name='이언일', role='owner', department='건자재유통사업팀(구매영업1Part)', phone='010-2594-4065', contact_email='eonil.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101167';
UPDATE profiles SET full_name='이재호', role='owner', department='원주공장품질관리실', phone='010-3773-6047', contact_email='jaeho3.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101169';
UPDATE profiles SET full_name='이철홍', role='controller', department='정관공장품질관리실', phone='010-4580-7438', contact_email='cheolhong.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101170';
UPDATE profiles SET full_name='이은수', role='owner', department='김해공장품질관리실', phone='010-5744-7763', contact_email='eunsu.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101171';
UPDATE profiles SET full_name='임재육', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-8575-2745', contact_email='jaeyuck.lim@tongyanginc.co.kr', is_active=true WHERE employee_id='101172';
UPDATE profiles SET full_name='장정훈', role='controller', department='원주공장품질관리실', phone='010-8489-4264', contact_email='jeonghoon.jang@tongyanginc.co.kr', is_active=true WHERE employee_id='101175';
UPDATE profiles SET full_name='정선우', role='owner', department='기술관리팀', phone='010-3656-0394', contact_email='sunwoo.jeong@tongyanginc.co.kr', is_active=true WHERE employee_id='101176';
UPDATE profiles SET full_name='정성민', role='owner', department='DC 프리콘 TFT', phone='010-9921-5737', contact_email='sungmin.jung@tongyanginc.co.kr', is_active=true WHERE employee_id='101177';
UPDATE profiles SET full_name='조재철', role='owner', department='공사관리팀', phone='010-8284-0890', contact_email='jaecheol.cho@tongyanginc.co.kr', is_active=true WHERE employee_id='101179';
UPDATE profiles SET full_name='진소환', role='owner', department='총무팀', phone='010-2742-7780', contact_email='sohwan.jin@tongyanginc.co.kr', is_active=true WHERE employee_id='101180';
UPDATE profiles SET full_name='최강석', role='owner', department='군산공장영업팀', phone='010-4001-0108', contact_email='kangseok.choi@tongyanginc.co.kr', is_active=true WHERE employee_id='101181';
UPDATE profiles SET full_name='홍정미', role='owner', department='연구개발팀', phone='010-4052-4319', contact_email='jungmi.hong@tongyanginc.co.kr', is_active=true WHERE employee_id='101184';
UPDATE profiles SET full_name='Pham Ngoc Son', role='owner', department='회전기사업/VPC(관리Part)', phone='010-5175-5632', contact_email='son.phamngoc@tongyanginc.co.kr', is_active=true WHERE employee_id='101185';
UPDATE profiles SET full_name='강태중', role='owner', department='울산공장영업팀', phone='010-8569-0782', contact_email='taejoong.kang@tongyanginc.co.kr', is_active=true WHERE employee_id='101187';
UPDATE profiles SET full_name='권대순', role='owner', department='연구개발팀', phone='010-7412-7144', contact_email='daesoon.kwon@tongyanginc.co.kr', is_active=true WHERE employee_id='101188';
UPDATE profiles SET full_name='권오윤', role='owner', department='전략기획팀', phone='010-3888-2059', contact_email='oykwon@tongyanginc.co.kr', is_active=true WHERE employee_id='101189';
UPDATE profiles SET full_name='권윤', role='owner', department='법무팀', phone='010-3482-2238', contact_email='yoon.guon@tongyanginc.co.kr', is_active=true WHERE employee_id='101190';
UPDATE profiles SET full_name='권혁준', role='owner', department='원주공장영업팀', phone='010-8531-0790', contact_email='hj.kwon@tongyanginc.co.kr', is_active=true WHERE employee_id='101191';
UPDATE profiles SET full_name='김경국', role='owner', department='골재사업소영업팀', phone='010-4433-4722', contact_email='kyoungkoog.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101194';
UPDATE profiles SET full_name='김경현', role='owner', department='부산공장품질관리실', phone='010-3508-7387', contact_email='kyounghyun.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101195';
UPDATE profiles SET full_name='김동석', role='owner', department='울산공장품질관리실', phone='010-3909-6087', contact_email='dongsuk.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101197';
UPDATE profiles SET full_name='김동혁', role='owner', department='회전기사업/VPC(설계Part)', phone='010-9655-7831', contact_email='donghyuk3.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101198';
UPDATE profiles SET full_name='김명학', role='owner', department='파주공장영업팀', phone='010-8790-0035', contact_email='mhkim76@tongyanginc.co.kr', is_active=true WHERE employee_id='101199';
UPDATE profiles SET full_name='김민성', role='owner', department='예산공장(생산관리Part)', phone='010-2832-7971', contact_email='minsung.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101200';
UPDATE profiles SET full_name='김민재', role='owner', department='총무팀', phone='010-2391-2349', contact_email='apple@tongyanginc.co.kr', is_active=true WHERE employee_id='101201';
UPDATE profiles SET full_name='김병국', role='owner', department='전주공장품질관리실', phone='010-2536-6656', contact_email='byungkuk.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101203';
UPDATE profiles SET full_name='김성목', role='owner', department='부산공장품질관리실', phone='010-4789-0061', contact_email='sungmok.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101205';
UPDATE profiles SET full_name='김주현', role='owner', department='부산공장관리팀', phone='010-3279-7272', contact_email='juhyun2.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101207';
UPDATE profiles SET full_name='김화겸', role='owner', department='군산공장품질관리실', phone='010-3111-9448', contact_email='hwakyum.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101208';
