UPDATE profiles SET full_name='김시영', role='owner', department='서부산공장공정팀', phone='010-4105-2246', contact_email='kimsy@tongyanginc.co.kr', is_active=true WHERE employee_id='101846';
UPDATE profiles SET full_name='문준혁', role='owner', department='예산공장(생산관리Part)', phone='010-2032-7859', contact_email='jhm@tongyanginc.co.kr', is_active=true WHERE employee_id='101850';
UPDATE profiles SET full_name='민영규', role='owner', department='가마지천 수해상습지 개선공사', phone='010-2112-9097', contact_email='myg@tongyanginc.co.kr', is_active=true WHERE employee_id='101857';
UPDATE profiles SET full_name='신홍겸', role='owner', department='부산공장공정팀', phone='010-4344-4252', contact_email='shinhonggyeom@tongyanginc.co.kr', is_active=true WHERE employee_id='101859';
UPDATE profiles SET full_name='이승진', role='owner', department='골재사업소부산크라샤공정팀', phone='010-2565-7556', contact_email='lsj@tongyanginc.co.kr', is_active=true WHERE employee_id='101866';
UPDATE profiles SET full_name='공광호', role='owner', department='아산공장', phone='010-2756-8903', contact_email='gongkh@tongyanginc.co.kr', is_active=true WHERE employee_id='101869';
UPDATE profiles SET full_name='김재석', role='owner', department='회전기사업/VPC(설계Part)', phone='010-8631-3548', contact_email='kjs@tongyanginc.co.kr', is_active=true WHERE employee_id='101871';
UPDATE profiles SET full_name='송지수', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-5665-0634', contact_email='sjs0634@tongyanginc.co.kr', is_active=true WHERE employee_id='101878';
UPDATE profiles SET full_name='홍성호', role='controller', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-3367-6629', contact_email='shhong@tongyanginc.co.kr', is_active=true WHERE employee_id='101880';
UPDATE profiles SET full_name='배중완', role='owner', department='개발사업팀', phone='010-5144-8371', contact_email='jwbae@tongyanginc.co.kr', is_active=true WHERE employee_id='101885';
UPDATE profiles SET full_name='정기영', role='owner', department='인천공장공정팀', phone='010-2265-0844', contact_email='jgy@tongyanginc.co.kr', is_active=true WHERE employee_id='101886';
UPDATE profiles SET full_name='김현기', role='owner', department='전주공장공정팀', phone='010-8642-2458', contact_email='khg@tongyanginc.co.kr', is_active=true WHERE employee_id='101887';
UPDATE profiles SET full_name='최명진', role='owner', department='아산공장공정팀', phone='010-2300-3834', contact_email='cmj@tongyanginc.co.kr', is_active=true WHERE employee_id='101888';
UPDATE profiles SET full_name='김형신', role='owner', department='김해공장공정팀', phone='010-7305-2270', contact_email='khs@tongyanginc.co.kr', is_active=true WHERE employee_id='101889';
UPDATE profiles SET full_name='김문곤', role='owner', department='안양공장공정팀', phone='010-5043-8656', contact_email='kmg@tongyanginc.co.kr', is_active=true WHERE employee_id='101890';
UPDATE profiles SET full_name='손승복', role='owner', department='파주공장공정팀', phone='010-2410-2869', contact_email='ssb@tongyanginc.co.kr', is_active=true WHERE employee_id='101891';
UPDATE profiles SET full_name='조현', role='owner', department='서부산공장공정팀', phone='010-4804-4700', contact_email='joh@tongyanginc.co.kr', is_active=true WHERE employee_id='101892';
UPDATE profiles SET full_name='변대룡', role='owner', department='광양 바이오매스 EPC 건설공사', phone='010-3151-5856', contact_email='bdr@tongyanginc.co.kr', is_active=true WHERE employee_id='101893';
UPDATE profiles SET full_name='정진이', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-4007-1030', contact_email='jjy@tongyanginc.co.kr', is_active=true WHERE employee_id='101894';
UPDATE profiles SET full_name='민명일', role='owner', department='산포처리구역 하수관로 정비사업', phone='010-2627-6858', contact_email='mmi@tongyanginc.co.kr', is_active=true WHERE employee_id='101900';
UPDATE profiles SET full_name='박재찬', role='owner', department='중곡-1 소구역 하수관로 정비공사(3권역)', phone='010-7231-2772', contact_email='pjc@tongyanginc.co.kr', is_active=true WHERE employee_id='101901';
UPDATE profiles SET full_name='박선재', role='owner', department='중곡-1 소구역 하수관로 정비공사(3권역)', phone='010-3739-1015', contact_email='psj@tongyanginc.co.kr', is_active=true WHERE employee_id='101902';
UPDATE profiles SET full_name='이상도', role='owner', department='서부산공장', phone='010-9795-2482', contact_email='lsd1@tongyanginc.co.kr', is_active=true WHERE employee_id='101903';
UPDATE profiles SET full_name='류희수', role='owner', department='사업관리팀', phone='010-5239-6002', contact_email='rhs@tongyanginc.co.kr', is_active=true WHERE employee_id='101904';
UPDATE profiles SET full_name='이준호', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-2040-8866', contact_email='jhl@tongyanginc.co.kr', is_active=true WHERE employee_id='101907';
UPDATE profiles SET full_name='윤충훈', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-4399-5907', contact_email='ych@tongyanginc.co.kr', is_active=true WHERE employee_id='101908';
UPDATE profiles SET full_name='정용섭', role='owner', department='공사관리팀', phone='010-5229-4442', contact_email='jys@tongyanginc.co.kr', is_active=true WHERE employee_id='101909';
UPDATE profiles SET full_name='이다영', role='owner', department='사업관리팀', phone='010-7547-4056', contact_email='ldy@tongyanginc.co.kr', is_active=true WHERE employee_id='101912';
UPDATE profiles SET full_name='이용일', role='owner', department='사업관리팀', phone='010-6534-4577', contact_email='lyi@tongyanginc.co.kr', is_active=true WHERE employee_id='101913';
UPDATE profiles SET full_name='조웅진', role='owner', department='김포공장품질관리실', phone='010-2961-0434', contact_email='cwj@tongyanginc.co.kr', is_active=true WHERE employee_id='101915';
UPDATE profiles SET full_name='김진석', role='owner', department='울산공장품질관리실', phone='010-2570-5918', contact_email='jskim@tongyanginc.co.kr', is_active=true WHERE employee_id='101917';
UPDATE profiles SET full_name='김성민', role='owner', department='중곡-1 소구역 하수관로 정비공사(3권역)', phone='010-8770-6462', contact_email='smkim@tongyanginc.co.kr', is_active=true WHERE employee_id='101918';
UPDATE profiles SET full_name='송윤성', role='owner', department='서부산공장품질관리실', phone='010-5428-5073', contact_email='yssong@tongyanginc.co.kr', is_active=true WHERE employee_id='101919';
UPDATE profiles SET full_name='신정항', role='owner', department='안양공장영업팀', phone='010-9337-6145', contact_email='shinjh@tongyanginc.co.kr', is_active=true WHERE employee_id='101921';
UPDATE profiles SET full_name='한영일', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-9075-5608', contact_email='hyi1@tongyanginc.co.kr', is_active=true WHERE employee_id='101922';
UPDATE profiles SET full_name='김정임', role='owner', department='중곡-1 소구역 하수관로 정비공사(3권역)', phone='010-4767-1789', contact_email='kjn@tongyanginc.co.kr', is_active=true WHERE employee_id='101923';
UPDATE profiles SET full_name='김재덕', role='owner', department='한국건강관리협회 인천광역시지부 건립 소방공사', phone='010-8866-7532', contact_email='kjd@tongyanginc.co.kr', is_active=true WHERE employee_id='101924';
UPDATE profiles SET full_name='이제원', role='owner', department='가마지천 수해상습지 개선공사', phone='010-3200-6173', contact_email='ljw@tongyanginc.co.kr', is_active=true WHERE employee_id='101925';
UPDATE profiles SET full_name='손규진', role='owner', department='부산공장공정팀', phone='010-3623-4569', contact_email='sgj@tongyanginc.co.kr', is_active=true WHERE employee_id='101926';
UPDATE profiles SET full_name='안진현', role='owner', department='제주공장공정팀', phone='010-4692-3009', contact_email='ajh@tongyanginc.co.kr', is_active=true WHERE employee_id='101927';
UPDATE profiles SET full_name='김성준', role='owner', department='골재사업소부산크라샤공정팀', phone='010-2632-1039', contact_email='ksj@tongyanginc.co.kr', is_active=true WHERE employee_id='101928';
UPDATE profiles SET full_name='정홍재', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-4189-8277', contact_email='jhj@tongyanginc.co.kr', is_active=true WHERE employee_id='101930';
UPDATE profiles SET full_name='정주원', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-3897-4129', contact_email='jwj@tongyanginc.co.kr', is_active=true WHERE employee_id='101932';
UPDATE profiles SET full_name='오희열', role='owner', department='회전기영업팀(영업2Part)', phone='010-4064-9051', contact_email='heeyul.oh@tongyanginc.co.kr', is_active=true WHERE employee_id='101933';
UPDATE profiles SET full_name='김덕훈', role='owner', department='원주공장공정팀', phone='010-8686-2370', contact_email='kdh@tongyanginc.co.kr', is_active=true WHERE employee_id='101934';
UPDATE profiles SET full_name='김효정', role='owner', department='광양 바이오매스 EPC 건설공사', phone='010-5534-3727', contact_email='hjk@tongyanginc.co.kr', is_active=true WHERE employee_id='101936';
UPDATE profiles SET full_name='이석원', role='owner', department='가마지천 수해상습지 개선공사', phone='010-7274-4918', contact_email='leesw1@tongyanginc.co.kr', is_active=true WHERE employee_id='101939';
UPDATE profiles SET full_name='이충현', role='owner', department='안양공장영업팀', phone='010-3934-0228', contact_email='chl@tongyanginc.co.kr', is_active=true WHERE employee_id='101945';
UPDATE profiles SET full_name='강지훈', role='owner', department='김포공장품질관리실', phone='010-5135-5101', contact_email='kjh2@tongyanginc.co.kr', is_active=true WHERE employee_id='101951';
UPDATE profiles SET full_name='조진현', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-4101-6489', contact_email='jjh1@tongyanginc.co.kr', is_active=true WHERE employee_id='101952';
