UPDATE profiles SET full_name='박문수', role='controller', department='서부산공장품질관리실', phone='010-3815-9888', contact_email='moonsoo.park@tongyanginc.co.kr', is_active=true WHERE employee_id='101074';
UPDATE profiles SET full_name='박병보', role='owner', department='창원공장품질관리실', phone='010-3151-2060', contact_email='byungbo.park@tongyanginc.co.kr', is_active=true WHERE employee_id='101075';
UPDATE profiles SET full_name='박상민', role='owner', department='채권관리팀', phone='010-7184-5990', contact_email='sangmin2.park@tongyanginc.co.kr', is_active=true WHERE employee_id='101076';
UPDATE profiles SET full_name='박준만', role='controller', department='파주공장품질관리실', phone='010-6279-0665', contact_email='TMJ_1005434@tongyanginc.co.kr', is_active=true WHERE employee_id='101077';
UPDATE profiles SET full_name='배경희', role='owner', department='인사팀', phone='010-5493-0090', contact_email='khbae@tongyanginc.co.kr', is_active=true WHERE employee_id='101078';
UPDATE profiles SET full_name='백낙동', role='owner', department='원주공장품질관리실', phone='010-5359-7212', contact_email='rakdong.baek@tongyanginc.co.kr', is_active=true WHERE employee_id='101079';
UPDATE profiles SET full_name='서상효', role='owner', department='P.I TFT', phone='010-8595-1658', contact_email='sanghyo.seo@tongyanginc.co.kr', is_active=true WHERE employee_id='101080';
UPDATE profiles SET full_name='성항수', role='owner', department='정관공장품질관리실', phone='010-2564-2417', contact_email='hangsoo.sung@tongyanginc.co.kr', is_active=true WHERE employee_id='101082';
UPDATE profiles SET full_name='안태현', role='controller', department='건자재유통사업팀', phone='010-8532-3021', contact_email='taehyun.ahn@tongyanginc.co.kr', is_active=true WHERE employee_id='101084';
UPDATE profiles SET full_name='유석상', role='controller', department='아산공장품질관리실', phone='010-6208-4658', contact_email='seoksang.yoo@tongyanginc.co.kr', is_active=true WHERE employee_id='101087';
UPDATE profiles SET full_name='유진오', role='owner', department='회전기사업/VPC(설계Part)', phone='010-3408-7650', contact_email='jino.yu@tongyanginc.co.kr', is_active=true WHERE employee_id='101089';
UPDATE profiles SET full_name='윤종환', role='owner', department='재무담당', phone='010-3872-1088', contact_email='jonghwan.yoon@tongyanginc.co.kr', is_active=true WHERE employee_id='101090';
UPDATE profiles SET full_name='이명재', role='owner', department='파주공장관리팀', phone='010-6366-7784', contact_email='myungjae.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101091';
UPDATE profiles SET full_name='이백열', role='owner', department='창원공장관리팀', phone='010-8501-0778', contact_email='backyeol.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101092';
UPDATE profiles SET full_name='이병남', role='controller', department='예산공장(품질보증Part)', phone='010-8941-8075', contact_email='byoungnam.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101093';
UPDATE profiles SET full_name='이상원', role='owner', department='공사관리팀', phone='010-3667-9617', contact_email='sangwon.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101095';
UPDATE profiles SET full_name='이영우', role='owner', department='공사관리팀', phone='010-7275-7195', contact_email='youngwoo.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101097';
UPDATE profiles SET full_name='이재찬', role='owner', department='회전기영업팀(영업2Part)', phone='010-3272-5754', contact_email='jaechan.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101098';
UPDATE profiles SET full_name='이종석', role='owner', department='사업운영팀', phone='010-3162-1700', contact_email='jongseok3.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101099';
UPDATE profiles SET full_name='이해일', role='controller', department='창원공장품질관리실', phone='010-8515-3893', contact_email='haeil.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101100';
UPDATE profiles SET full_name='임지영', role='controller', department='회계팀', phone='010-5386-6673', contact_email='jiyoung.im@tongyanginc.co.kr', is_active=true WHERE employee_id='101103';
UPDATE profiles SET full_name='장경남', role='controller', department='인천공장품질관리실', phone='010-7340-9486', contact_email='midas@tongyanginc.co.kr', is_active=true WHERE employee_id='101104';
UPDATE profiles SET full_name='장백호', role='controller', department='양산공장품질관리실', phone='010-4589-8824', contact_email='backho.jang@tongyanginc.co.kr', is_active=true WHERE employee_id='101105';
UPDATE profiles SET full_name='장철호', role='controller', department='총무팀', phone='010-6424-7893', contact_email='cheolho.jang@tongyanginc.co.kr', is_active=true WHERE employee_id='101107';
UPDATE profiles SET full_name='전장규', role='controller', department='법무팀', phone='010-4506-6153', contact_email='janggyu.jeon@tongyanginc.co.kr', is_active=true WHERE employee_id='101108';
UPDATE profiles SET full_name='정병문', role='owner', department='P.I TFT', phone='010-8220-0408', contact_email='moon2@tongyanginc.co.kr', is_active=true WHERE employee_id='101109';
UPDATE profiles SET full_name='정성준', role='owner', department='양산공장품질관리실', phone='010-2605-4997', contact_email='sungjoon.jeong@tongyanginc.co.kr', is_active=true WHERE employee_id='101110';
UPDATE profiles SET full_name='조성천', role='owner', department='광양 바이오매스 EPC 건설공사', phone='010-3463-9645', contact_email='sungchun.cho@tongyanginc.co.kr', is_active=true WHERE employee_id='101111';
UPDATE profiles SET full_name='최낙만', role='owner', department='기술관리팀', phone='010-3645-8665', contact_email='nakman.choi@tongyanginc.co.kr', is_active=true WHERE employee_id='101113';
UPDATE profiles SET full_name='최낙용', role='owner', department='건자재유통사업팀(중부영업Part)', phone='010-8627-8591', contact_email='rakyong.choi@tongyanginc.co.kr', is_active=true WHERE employee_id='101114';
UPDATE profiles SET full_name='최종익', role='owner', department='김포공장관리팀', phone='010-3353-6344', contact_email='jongik.choi@tongyanginc.co.kr', is_active=true WHERE employee_id='101115';
UPDATE profiles SET full_name='최종태', role='owner', department='안양공장관리팀', phone='010-7345-3982', contact_email='jongtae.choi@tongyanginc.co.kr', is_active=true WHERE employee_id='101116';
UPDATE profiles SET full_name='하정훈', role='controller', department='내부회계팀', phone='010-8929-2281', contact_email='jeonghun.ha@tongyanginc.co.kr', is_active=true WHERE employee_id='101119';
UPDATE profiles SET full_name='한오영', role='owner', department='건자재유통사업팀(수도권영업Part)', phone='010-5493-3717', contact_email='ohyoung.han@tongyanginc.co.kr', is_active=true WHERE employee_id='101120';
UPDATE profiles SET full_name='한재원', role='owner', department='예산공장(생산관리Part)', phone='010-5165-2053', contact_email='jaewon.han@tongyanginc.co.kr', is_active=true WHERE employee_id='101121';
UPDATE profiles SET full_name='황동규', role='owner', department='예산공장(회전기안전Part)', phone='010-5634-2593', contact_email='donggyu.hwang@tongyanginc.co.kr', is_active=true WHERE employee_id='101122';
UPDATE profiles SET full_name='강진식', role='owner', department='파주공장품질관리실', phone='010-4238-0975', contact_email='jinsig.kang@tongyanginc.co.kr', is_active=true WHERE employee_id='101123';
UPDATE profiles SET full_name='공옥환', role='owner', department='예산공장(회전기안전Part)', phone='010-5454-0354', contact_email='okhwan.kong@tongyanginc.co.kr', is_active=true WHERE employee_id='101125';
UPDATE profiles SET full_name='곽승환', role='owner', department='DC 프리콘 TFT', phone='010-6450-1523', contact_email='kshabcd@tongyanginc.co.kr', is_active=true WHERE employee_id='101126';
UPDATE profiles SET full_name='권용진', role='owner', department='회전기영업팀(영업1Part)', phone='010-6543-4687', contact_email='yongjin.kwon@tongyanginc.co.kr', is_active=true WHERE employee_id='101127';
UPDATE profiles SET full_name='김민성', role='owner', department='DC 프리콘 TFT', phone='010-2667-8680', contact_email='minsung2.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101129';
UPDATE profiles SET full_name='김상우', role='controller', department='자금팀', phone='010-8254-5675', contact_email='sangwoo.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101130';
UPDATE profiles SET full_name='김석권', role='owner', department='건자재유통사업팀(구매영업2Part)', phone='010-8212-5793', contact_email='seokkwon.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101131';
UPDATE profiles SET full_name='김성수', role='owner', department='안양공장영업팀', phone='010-3825-2884', contact_email='sungsoo3.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101133';
UPDATE profiles SET full_name='김은영', role='owner', department='아산공장영업팀', phone='010-5424-1836', contact_email='eunyoung2.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101134';
UPDATE profiles SET full_name='김재명', role='owner', department='광양 바이오매스 EPC 건설공사', phone='010-3035-0017', contact_email='jmkim@tongyanginc.co.kr', is_active=true WHERE employee_id='101135';
UPDATE profiles SET full_name='김종국', role='owner', department='안양공장품질관리실', phone='010-5457-9134', contact_email='jongkoog.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101136';
UPDATE profiles SET full_name='김태우', role='owner', department='대구공장관리팀', phone='010-4545-0205', contact_email='taewoo3.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101137';
UPDATE profiles SET full_name='김태형', role='owner', department='골재사업소영업팀', phone='010-4561-0440', contact_email='na77kth@tongyanginc.co.kr', is_active=true WHERE employee_id='101138';
UPDATE profiles SET full_name='김형완', role='owner', department='회전기사업/VPC', phone='010-9357-1504', contact_email='hwkim98@tongyanginc.co.kr', is_active=true WHERE employee_id='101139';
