UPDATE profiles SET full_name='김윤기', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-6309-2756', contact_email='ykkim@tongyanginc.co.kr', is_active=true WHERE employee_id='101953';
UPDATE profiles SET full_name='이해창', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-4045-4715', contact_email='hclee@tongyanginc.co.kr', is_active=true WHERE employee_id='101954';
UPDATE profiles SET full_name='이소형', role='owner', department='인사팀', phone='010-8331-3653', contact_email='shl@tongyanginc.co.kr', is_active=true WHERE employee_id='101955';
UPDATE profiles SET full_name='김진용', role='owner', department='환경안전팀', phone='010-4355-5332', contact_email='jykim@eugenes.co.kr', is_active=true WHERE employee_id='101956';
UPDATE profiles SET full_name='조승범', role='owner', department='개발운영팀', phone='010-6312-0302', contact_email='cho@tongyanginc.co.kr', is_active=true WHERE employee_id='101957';
UPDATE profiles SET full_name='김진수', role='owner', department='개발운영팀', phone='010-6292-6979', contact_email='Kimjs4521@tongyanginc.co.kr', is_active=true WHERE employee_id='101958';
UPDATE profiles SET full_name='최세운', role='owner', department='개발운영팀', phone='010-6516-0729', contact_email='seawoon@tongyanginc.co.kr', is_active=true WHERE employee_id='101959';
UPDATE profiles SET full_name='강상현', role='owner', department='개발사업팀', phone='010-6295-5759', contact_email='kangsanghyeon@tongyanginc.co.kr', is_active=true WHERE employee_id='101960';
UPDATE profiles SET full_name='오세중', role='owner', department='개발사업팀', phone='010-5629-3326', contact_email='se3326@tongyanginc.co.kr', is_active=true WHERE employee_id='101961';
UPDATE profiles SET full_name='이시윤', role='owner', department='양산공장공정팀', phone='010-8559-9450', contact_email='sylee1@tongyanginc.co.kr', is_active=true WHERE employee_id='101962';
UPDATE profiles SET full_name='홍정수', role='owner', department='부산공장영업팀', phone='010-3151-3805', contact_email='jshong@tongyanginc.co.kr', is_active=true WHERE employee_id='101963';
UPDATE profiles SET full_name='문병민', role='owner', department='일산수질복원센터 시설개량사업 [1단계](토목, 건축, 기계분야)', phone='010-8487-2123', contact_email='mbm@tongyanginc.co.kr', is_active=true WHERE employee_id='101965';
UPDATE profiles SET full_name='장소영', role='owner', department='개발운영팀', phone='010-3634-7434', contact_email='jsy1@tongyanginc.co.kr', is_active=true WHERE employee_id='101966';
UPDATE profiles SET full_name='김지연', role='owner', department='보령발전본부 저탄장 옥내화사업 토목공사', phone='010-9803-3572', contact_email='kjy@tongyanginc.co.kr', is_active=true WHERE employee_id='101968';
UPDATE profiles SET full_name='송윤정', role='owner', department='P.I TFT', phone='010-9428-8397', contact_email='yjsong@tongyanginc.co.kr', is_active=true WHERE employee_id='101971';
UPDATE profiles SET full_name='이호선', role='owner', department='인천공장공정팀', phone='010-3683-5719', contact_email='hslee1@tongyanginc.co.kr', is_active=true WHERE employee_id='101972';
UPDATE profiles SET full_name='박시환', role='owner', department='자금팀', phone='010-5227-8860', contact_email='shpark@tongyanginc.co.kr', is_active=true WHERE employee_id='101973';
UPDATE profiles SET full_name='최종현', role='owner', department='내부회계팀', phone='010-5234-9212', contact_email='jhchoi1@tongyanginc.co.kr', is_active=true WHERE employee_id='101974';
UPDATE profiles SET full_name='김상국', role='owner', department='파주공장공정팀', phone='010-5154-1922', contact_email='kimsk@tongyanginc.co.kr', is_active=true WHERE employee_id='101975';
UPDATE profiles SET full_name='임상혁', role='owner', department='아산공장공정팀', phone='010-6638-0727', contact_email='shim@tongyanginc.co.kr', is_active=true WHERE employee_id='101976';
UPDATE profiles SET full_name='장원웅', role='owner', department='원주공장공정팀', phone='010-5372-3942', contact_email='wwjang@tongyanginc.co.kr', is_active=true WHERE employee_id='101977';
UPDATE profiles SET full_name='이동희', role='owner', department='창원공장공정팀', phone='010-8206-5449', contact_email='leedh@tongyanginc.co.kr', is_active=true WHERE employee_id='101978';
UPDATE profiles SET full_name='남윤호', role='owner', department='부산공장품질관리실', phone='010-6693-1431', contact_email='nyh@tongyanginc.co.kr', is_active=true WHERE employee_id='101980';
UPDATE profiles SET full_name='김성용', role='owner', department='정관공장', phone='010-5453-8353', contact_email='ksy8353@tongyanginc.co.kr', is_active=true WHERE employee_id='101981';
UPDATE profiles SET full_name='정해종', role='owner', department='원주공장품질관리실', phone='010-5313-5470', contact_email='junghj@tongyanginc.co.kr', is_active=true WHERE employee_id='101982';
UPDATE profiles SET full_name='김휘영', role='owner', department='아산공장관리팀', phone='', contact_email='', is_active=true WHERE employee_id='109980';
