UPDATE profiles SET full_name='이현기', role='owner', department='인천공장공정팀', phone='010-3746-8786', contact_email='lhk@tongyanginc.co.kr', is_active=true WHERE employee_id='101558';
UPDATE profiles SET full_name='윤태환', role='owner', department='골재사업소서부산크라샤공정팀', phone='010-4368-2727', contact_email='yth@tongyanginc.co.kr', is_active=true WHERE employee_id='101559';
UPDATE profiles SET full_name='최재환', role='owner', department='정관공장공정팀', phone='010-3654-4973', contact_email='cjh@tongyanginc.co.kr', is_active=true WHERE employee_id='101560';
UPDATE profiles SET full_name='이우현', role='owner', department='아산공장공정팀', phone='010-3739-5415', contact_email='lwh@tongyanginc.co.kr', is_active=true WHERE employee_id='101561';
UPDATE profiles SET full_name='임영택', role='owner', department='전략기획팀', phone='010-6395-0020', contact_email='ytlim@tongyanginc.co.kr', is_active=true WHERE employee_id='101564';
UPDATE profiles SET full_name='김규식', role='owner', department='DC 프리콘 TFT', phone='010-4187-4982', contact_email='kks@tongyanginc.co.kr', is_active=true WHERE employee_id='101572';
UPDATE profiles SET full_name='박만수', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-3837-8839', contact_email='mspark@tongyanginc.co.kr', is_active=true WHERE employee_id='101573';
UPDATE profiles SET full_name='박팔진', role='owner', department='김해공장', phone='010-2731-3580', contact_email='ppj@tongyanginc.co.kr', is_active=true WHERE employee_id='101576';
UPDATE profiles SET full_name='박영상', role='owner', department='정관공장품질관리실', phone='010-7187-7560', contact_email='pys@tongyanginc.co.kr', is_active=true WHERE employee_id='101577';
UPDATE profiles SET full_name='이수민', role='owner', department='자금팀', phone='010-9988-1628', contact_email='leesumin423@tongyanginc.co.kr', is_active=true WHERE employee_id='101579';
UPDATE profiles SET full_name='한해덕', role='owner', department='양산공장관리팀', phone='010-6616-6359', contact_email='duck6359@tongyanginc.co.kr', is_active=true WHERE employee_id='101584';
UPDATE profiles SET full_name='정택윤', role='owner', department='안양공장품질관리실', phone='010-2534-2832', contact_email='xordbs2832@tongyanginc.co.kr', is_active=true WHERE employee_id='101585';
UPDATE profiles SET full_name='이상우', role='owner', department='정관공장품질관리실', phone='010-2036-1417', contact_email='lsw@tongyanginc.co.kr', is_active=true WHERE employee_id='101586';
UPDATE profiles SET full_name='황인철', role='owner', department='부산공장품질관리실', phone='010-9465-7813', contact_email='hic3863@tongyanginc.co.kr', is_active=true WHERE employee_id='101591';
UPDATE profiles SET full_name='임남혁', role='owner', department='공사관리팀', phone='010-3650-5239', contact_email='lnh@tongyanginc.co.kr', is_active=true WHERE employee_id='101595';
UPDATE profiles SET full_name='김대웅', role='owner', department='한국건강관리협회 인천지부 신청사 건립 신축공사', phone='010-9616-0441', contact_email='kdw@tongyanginc.co.kr', is_active=true WHERE employee_id='101602';
UPDATE profiles SET full_name='이원중', role='owner', department='그룹파견', phone='010-4564-1213', contact_email='lwj@tongyanginc.co.kr', is_active=true WHERE employee_id='101608';
UPDATE profiles SET full_name='전상조', role='owner', department='군산공장공정팀', phone='010-8854-2515', contact_email='jsj@tongyanginc.co.kr', is_active=true WHERE employee_id='101616';
UPDATE profiles SET full_name='이병록', role='owner', department='부산공장공정팀', phone='010-5175-1420', contact_email='lbr@tongyanginc.co.kr', is_active=true WHERE employee_id='101617';
UPDATE profiles SET full_name='정식현', role='owner', department='정관공장공정팀', phone='010-3517-0048', contact_email='jsh2@tongyanginc.co.kr', is_active=true WHERE employee_id='101618';
UPDATE profiles SET full_name='최병석', role='owner', department='김해공장공정팀', phone='010-5181-7486', contact_email='cbs@tongyanginc.co.kr', is_active=true WHERE employee_id='101619';
UPDATE profiles SET full_name='성윤모', role='owner', department='안양공장공정팀', phone='010-9198-0177', contact_email='sym@tongyanginc.co.kr', is_active=true WHERE employee_id='101622';
UPDATE profiles SET full_name='이연지', role='owner', department='제주공장관리팀', phone='010-6710-2771', contact_email='lyj@tongyanginc.co.kr', is_active=true WHERE employee_id='101633';
UPDATE profiles SET full_name='김현재', role='owner', department='DC 프리콘 TFT', phone='010-8842-6403', contact_email='khj@tongyanginc.co.kr', is_active=true WHERE employee_id='101634';
UPDATE profiles SET full_name='임영록', role='owner', department='서부산공장품질관리실', phone='010-9332-1603', contact_email='lyr1603@tongyanginc.co.kr', is_active=true WHERE employee_id='101636';
UPDATE profiles SET full_name='윤진효', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-9099-9886', contact_email='jinhyo@tongyanginc.co.kr', is_active=true WHERE employee_id='101638';
UPDATE profiles SET full_name='박준태', role='owner', department='예산공장(생산관리Part)', phone='010-7293-6793', contact_email='ak1100@tongyanginc.co.kr', is_active=true WHERE employee_id='101645';
UPDATE profiles SET full_name='이민호', role='owner', department='인천공장공정팀', phone='010-3269-3607', contact_email='lmh@tongyanginc.co.kr', is_active=true WHERE employee_id='101648';
UPDATE profiles SET full_name='고영욱', role='owner', department='골재사업소부산크라샤공정팀', phone='010-7332-3979', contact_email='ywk@tongyanginc.co.kr', is_active=true WHERE employee_id='101650';
UPDATE profiles SET full_name='김윤승', role='owner', department='전주공장공정팀', phone='010-8644-7545', contact_email='kws@tongyanginc.co.kr', is_active=true WHERE employee_id='101652';
UPDATE profiles SET full_name='장영채', role='owner', department='창원공장공정팀', phone='010-2418-5459', contact_email='jyc@tongyanginc.co.kr', is_active=true WHERE employee_id='101653';
UPDATE profiles SET full_name='배설목', role='owner', department='김해공장공정팀', phone='010-9765-8384', contact_email='bsm@tongyanginc.co.kr', is_active=true WHERE employee_id='101654';
UPDATE profiles SET full_name='정수일', role='owner', department='부산공장공정팀', phone='010-3388-4141', contact_email='jsi@tongyanginc.co.kr', is_active=true WHERE employee_id='101655';
UPDATE profiles SET full_name='서창진', role='owner', department='정관공장공정팀', phone='010-4930-0580', contact_email='scj@tongyanginc.co.kr', is_active=true WHERE employee_id='101656';
UPDATE profiles SET full_name='정병성', role='owner', department='군산공장공정팀', phone='010-9141-0815', contact_email='bsj@tongyanginc.co.kr', is_active=true WHERE employee_id='101657';
UPDATE profiles SET full_name='김범하', role='owner', department='공사관리팀', phone='010-9082-2709', contact_email='wisdom@tongyanginc.co.kr', is_active=true WHERE employee_id='101658';
UPDATE profiles SET full_name='이근용', role='owner', department='공사관리팀', phone='010-6293-3892', contact_email='gunyong@tongyanginc.co.kr', is_active=true WHERE employee_id='101666';
UPDATE profiles SET full_name='김진수', role='owner', department='양산공장공정팀', phone='010-3063-5918', contact_email='zhaqh2000@tongyanginc.co.kr', is_active=true WHERE employee_id='101667';
UPDATE profiles SET full_name='서민', role='owner', department='국회대로 지하차도 및 상부공원화(2단계)건설공사 1공구', phone='010-3310-5719', contact_email='seomin@tongyanginc.co.kr', is_active=true WHERE employee_id='101668';
UPDATE profiles SET full_name='고대섭', role='owner', department='개발사업팀', phone='010-5486-3297', contact_email='kds@tongyanginc.co.kr', is_active=true WHERE employee_id='101672';
UPDATE profiles SET full_name='김태현', role='owner', department='서대문 은평지사 복합사옥 신축공사', phone='010-5220-2906', contact_email='kth@tongyanginc.co.kr', is_active=true WHERE employee_id='101675';
UPDATE profiles SET full_name='송준석', role='owner', department='예산공장(회전기안전Part)', phone='010-4633-6530', contact_email='sjs@tongyanginc.co.kr', is_active=true WHERE employee_id='101676';
UPDATE profiles SET full_name='방영식', role='owner', department='김포공장영업팀', phone='010-5236-4322', contact_email='rabi32@tongyanginc.co.kr', is_active=true WHERE employee_id='101680';
UPDATE profiles SET full_name='임용범', role='owner', department='파주공장영업팀', phone='010-4065-0205', contact_email='oneshot0205@tongyanginc.co.kr', is_active=true WHERE employee_id='101681';
UPDATE profiles SET full_name='이승현', role='owner', department='김포공장품질관리실', phone='010-5225-4161', contact_email='seunghyun.lee@tongyanginc.co.kr', is_active=true WHERE employee_id='101682';
UPDATE profiles SET full_name='김남규', role='owner', department='김포공장영업팀', phone='010-9331-5272', contact_email='kbs5272@tongyanginc.co.kr', is_active=true WHERE employee_id='101683';
UPDATE profiles SET full_name='김동주', role='owner', department='김포공장품질관리실', phone='010-4787-5221', contact_email='dongju.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101686';
UPDATE profiles SET full_name='정성연', role='owner', department='김포공장영업팀', phone='010-8283-6054', contact_email='sungyoun.jung@tongyanginc.co.kr', is_active=true WHERE employee_id='101687';
UPDATE profiles SET full_name='김승종', role='owner', department='김포공장공정팀', phone='010-9143-1713', contact_email='seungjong.kim@tongyanginc.co.kr', is_active=true WHERE employee_id='101688';
UPDATE profiles SET full_name='표종호', role='owner', department='김포공장공정팀', phone='010-9331-7825', contact_email='jongho.pyo@tongyanginc.co.kr', is_active=true WHERE employee_id='101689';
